version: 2
jobs:
  build:

    working_directory: ~/orders

    docker:
      - image: circleci/openjdk:17-buster-node-browsers

    steps:

      - checkout

      - restore_cache:

          key: orders-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: orders-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/orders-0.0.1-SNAPSHOT.jar